
services:
  # Load Balancer (Nginx)
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - rabbitmq
      - redis
      - app-1
      - app-2
      - app-3
    networks:
      - pubsub-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  # RabbitMQ cluster
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - pubsub-network

  # Redis for distributed caching
  redis:
    image: redis:6
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - pubsub-network

  # Application instances
  app-1:
    build: .
    environment:
      - INSTANCE_ID=1
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CALLBACK_URL=http://pubsub.wernernagy.hu/pubsub/youtube
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - pubsub-network

  app-2:
    build: .
    environment:
      - INSTANCE_ID=2
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CALLBACK_URL=http://pubsub.wernernagy.hu/pubsub/youtube
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - pubsub-network

  app-3:
    build: .
    environment:
      - INSTANCE_ID=3
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CALLBACK_URL=http://pubsub.wernernagy.hu/pubsub/youtube
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - pubsub-network

networks:
  pubsub-network:
    driver: bridge

volumes:
  rabbitmq-data:
  redis-data:
